#version: '3.6'

services:
  angular-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 4200:4200
    command: ng serve --host 0.0.0.0